# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protolint < Formula
  desc "Pluggable tool to enforce Protocol Buffer style and conventions"
  homepage "https://github.com/yoheimuta/protolint"
  version "0.34.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.34.1/protolint_0.34.1_Darwin_x86_64.tar.gz"
      sha256 "6564b1169ca103a78963e4716847eb17a75412a8ac63f59b5d3660014f4c73ed"
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.34.1/protolint_0.34.1_Darwin_arm64.tar.gz"
      sha256 "efa4b0bd9435fa9175c27e3a692b7a4d1a0404045b590d130d4f324aebaf36b3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.34.1/protolint_0.34.1_Linux_x86_64.tar.gz"
      sha256 "c223f785d86e54682d8f97eacb62e7722a9a2787cbfc5896107c945e16c042ae"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.34.1/protolint_0.34.1_Linux_arm64.tar.gz"
      sha256 "b08ebe3927041e5e290852730452b054e47bf698d60bb98dfc1660a458b44e1c"
    end
  end

  def install
    bin.install "protolint"
    bin.install "protoc-gen-protolint"
    prefix.install "LICENSE"
  end

  test do
    system "#{bin}/protolint", "version"
    system "#{bin}/protoc-gen-protolint", "version"
  end
end
