# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protolint < Formula
  desc "Pluggable tool to enforce Protocol Buffer style and conventions"
  homepage "https://github.com/yoheimuta/protolint"
  version "0.42.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.42.2/protolint_0.42.2_Darwin_x86_64.tar.gz"
      sha256 "ca5b991b645f5d6cf90e929316a747ff6dcbb6684ab31229b3ba180cd500318c"

      def install
        bin.install "protolint"
        bin.install "protoc-gen-protolint"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.42.2/protolint_0.42.2_Darwin_arm64.tar.gz"
      sha256 "2d51e612ea8b259a86fa962af1a64f4f16bb7413ff03eceef858d470d06c7b63"

      def install
        bin.install "protolint"
        bin.install "protoc-gen-protolint"
        prefix.install "LICENSE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.42.2/protolint_0.42.2_Linux_armv6.tar.gz"
      sha256 "0864edba48fb900e57ed9584912d66878d8d152f085b91b5f9896bbb2994b98a"

      def install
        bin.install "protolint"
        bin.install "protoc-gen-protolint"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.42.2/protolint_0.42.2_Linux_arm64.tar.gz"
      sha256 "aa133ba64bb28a71bef2bb4e114f31891f3801c484149b431f0b6d85314e7d49"

      def install
        bin.install "protolint"
        bin.install "protoc-gen-protolint"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.42.2/protolint_0.42.2_Linux_x86_64.tar.gz"
      sha256 "a2eb357412690fc8966f8280c0fc8da5b1865b9729b2e89bf31fe6d265c831e6"

      def install
        bin.install "protolint"
        bin.install "protoc-gen-protolint"
        prefix.install "LICENSE"
      end
    end
  end

  test do
    system "#{bin}/protolint", "version"
    system "#{bin}/protoc-gen-protolint", "version"
  end
end
