# This file was generated by GoReleaser. DO NOT EDIT.
class Protolint < Formula
  desc "A pluggable tool to enforce Protocol Buffer style and conventions."
  homepage "https://github.com/yoheimuta/protolint"
  version "0.25.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yoheimuta/protolint/releases/download/v0.25.1/protolint_0.25.1_Darwin_x86_64.tar.gz"
    sha256 "a3dd69eb3804e1a52874d35c9623cc3f948a9e0ec0dce820056b5b2daafe731f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/yoheimuta/protolint/releases/download/v0.25.1/protolint_0.25.1_Linux_x86_64.tar.gz"
      sha256 "db3df2c946ce3a0f56c18f491f3ab32d11fbd7659b451324dcabc8bbb623c9a7"
    end
  end

  def install
    bin.install "protolint"
    bin.install "protoc-gen-protolint"
    prefix.install "LICENSE"
  end

  test do
    system "#{bin}/protolint version"
    system "#{bin}/protoc-gen-protolint version"
  end
end
